version: '3.9'

services:
  db:
    image: pgvector/pgvector:0.8.0-pg17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    # environment:
    #   DB_URL: ${DB_URL}
    #   GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    #   PYTHONPATH: ${PYTHONPATH}
    env_file:
      - .env
    ports:
      - "8000:8000"
